[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mcc_token = "FDRy2jpKqXD5pp8Xj2arEbEm78nCEcRnKCmGxBTiFWxr"

[programs.devnet]
mcc_token = "FDRy2jpKqXD5pp8Xj2arEbEm78nCEcRnKCmGxBTiFWxr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
