[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mcd_token = "J9UwVmFEr7ujLcp19T8nqpDnpBLcDzpL4cpwh5TMSd36"

[programs.devnet]
mcd_token = "J9UwVmFEr7ujLcp19T8nqpDnpBLcDzpL4cpwh5TMSd36"

[programs.mainnet]
mcd_token = "McDVieuEFv5ucnM3C7p8wsT6LY8BAipKDrTG9HjAu3R"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
