[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
territory_nft = "ipYLo2aitVyNXGzCgpiaKKA2JLvtbBvMHiV7qKZTPVZ"

[programs.devnet]
territory_nft = "ipYLo2aitVyNXGzCgpiaKKA2JLvtbBvMHiV7qKZTPVZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
